package com.example.apps;

import java.util.ArrayList;
import java.util.List;

public final class AppsData {

    public static List<AppsEvent> getData() {
        List<AppsEvent> list = new ArrayList<>();
        list.add(new AppsEvent("TOP APPS", null, 0, AppsEvent.HEADER_TYPE));
        list.add(new AppsEvent("TikTok", "com.zhiliaoapp.musically", R.drawable.tiktok, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("TikTok Lite Videos", "com.zhiliaoapp.musically.go", R.drawable.tiktok, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("TikTok Lite", "com.ss.android.ugc.trill.go", R.drawable.tiktok_lite, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("TikTok Wall Picture", "com.ss.android.ugc.tiktok.livewallpaper", R.drawable.tiktok_wall, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Helo", "app.buzz.share", R.drawable.helo, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Helo Lite", "app.buzz.share.lite", R.drawable.helo_lite, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("LIKE", "video.like", R.drawable.like, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("LIKE  Lite", "video.like.lite", R.drawable.like_lite, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Kwai", "com.kwai.video", R.drawable.kwai, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("UCBrowser", "com.UCMobile.intl", R.drawable.ucb, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("UCBrowser Mini", "com.uc.browser.en", R.drawable.ucbm, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("UC Browser Turbo", "com.ucturbo", R.drawable.ucbt, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("BeautyPlus", "com.commsource.beautyplus", R.drawable.bp, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Beauty Plus Camera", "com.sweet.cameraselfie.sweetface.beauty.plus", R.drawable.bpc, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("AppLock", "com.domobile.applockwatcher", R.drawable.app_lock, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Cam Scanner", "com.intsig.camscanner", R.drawable.cam_scanner, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("CamScanner HD", "com.intsig.camscannerhd", R.drawable.cam_scanner, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("SHAREit", "com.lenovo.anyshare.gps", R.drawable.shareit, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Xender", "cn.xender", R.drawable.xender, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("LIVE ME APPS", null, 0, AppsEvent.HEADER_TYPE));
        list.add(new AppsEvent("Kiss Live", "com.rare.chat", R.drawable.kiss_live, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Bigo Live", "sg.bigo.live", R.drawable.bigo_live, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Vigo Video", "com.ss.android.ugc.boom", R.drawable.vigo, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Vigo Video Live Photo", "com.ss.android.ugc.boom.livewallpaper", R.drawable.vigo_photo, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("VMate", "com.uc.vmate", R.drawable.vmate, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("VMate Status", "com.uc.vmlite", R.drawable.vmate_status, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Cut Cut", "com.xprodev.cutcam", R.drawable.cut_cut, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("MagiCut", "com.energysh.onlinecamera1", R.drawable.magi_cut, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("All Video Downloader", "com.snowwhiteapps.downloader", R.drawable.avd, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Vigo Lite", "com.ss.android.ugc.boomlite", R.drawable.vigo_lite, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("UDictionary", "com.youdao.hindict", R.drawable.ud, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("LivU", "com.videochat.livu", R.drawable.livu, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("TO GET YOU APPS", null, 0, AppsEvent.HEADER_TYPE));
        list.add(new AppsEvent("Live Chat", "com.gotomate.livechat", R.drawable.live_chat, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Turbo VPN", "free.vpn.unblock.proxy.turbovpn", R.drawable.tvpn, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Turbo VPN Lite", "free.vpn.unblock.proxy.turbovpn.lite", R.drawable.tvpnl, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Zak Zak Pro", "com.live.videochat.india", R.drawable.zakp, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Zak Zak Live", "com.zakzak.live.chat", R.drawable.zakp, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Zak Zak Pro", "com.zakzak.lite.chat", R.drawable.zak_lite, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("NonoLive", "com.nono.android", R.drawable.nono, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Web novel", "com.qidian.Int.reader", R.drawable.webn, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Web novel Lite", "com.webnovel.lite", R.drawable.webnl, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Art of Conquest", "com.lilithgame.sgame.gp.oss", R.drawable.aoc, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Flash key board", "com.flashkeyboardtheme", R.drawable.fkb, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Cheez", "com.kakao.cheez", R.drawable.cheez, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("NewsDog", "com.newsdog", R.drawable.newsd, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("GAME APPS", null, 0, AppsEvent.HEADER_TYPE));
        list.add(new AppsEvent("PUBG", "com.tencent.ig", R.drawable.pubg, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("PUBG Mobile Lite", "com.tencent.iglite", R.drawable.pubgl, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Clash of Kings", "com.hcg.cok.gp", R.drawable.cok, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Clash of Kings The West", "com.hcg.ctw.gp", R.drawable.coktw, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Castle Clash", "com.igg.castleclash", R.drawable.cc, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Mobile Legends", "com.mobile.legends", R.drawable.mobl, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Mobile Legends Adventure", "com.moonton.mobilehero", R.drawable.mobla, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Ludo King", "com.ludo.king", R.drawable.lk, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Game of Sultans", "com.dc.hwsj", R.drawable.gos, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Mafia City", "com.yottagames.mafiawar", R.drawable.mcity, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Battle of Empires", "com.gameloft.android.ANMP.GloftGHHM", R.drawable.boe, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Arena of Valor", "com.ngame.allstar.eu", R.drawable.aov, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Ludo World", "com.tencent.ludosuperstar", R.drawable.ludow, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Stick Fight", "com.netease.ddsfna", R.drawable.stickf, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Life After", "com.netease.mrzhna", R.drawable.litea, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Rise of Kingdom", "com.lilithgame.roc.gp", R.drawable.rok, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Clash of Queens", "com.elex.coq.gp", R.drawable.coq, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Zombie World SLG 3D", "com.zombieshooting.survivalhunter.gun3d", R.drawable.zws, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Heroes War", "com.nexters.herowars", R.drawable.herow, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Art of Conquest", "com.lilithgame.sgame.gp.oss", R.drawable.aoc, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Dank Tanks", "com.lilithgame.tgames.gp", R.drawable.dankt, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("AFK Arena", "com.lilithgames.hgame.gp.id", R.drawable.akf, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Isoland 2 Ashes of Time", "com.lilithgame.isoland2.gpen", R.drawable.iaot, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Isoland 2 Ashes of Time Lite", "com.lilithgame.isoland2.gp.mf", R.drawable.iaot, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Identity V-Danganronpa first crossover has started", "com.netease.idv.googleplay", R.drawable.idfchs, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Warpath", "com.lilithgame.wgame.gp", R.drawable.war_path, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Cyber Hunter", "com.netease.lztgglobal", R.drawable.cyberh, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Cyber Hunter Lite", "com.netease.lztglite", R.drawable.cyberh, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Soul Hunters", "us.kick9.k3000000013.c3101000001", R.drawable.soulh, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Mr Pumpkin 2: Walls of Kowloon", "com.lilithgames.mrpumpkin2.gp", R.drawable.mpwok, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Creative Destruction", "com.titan.cd.gb", R.drawable.cd, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Chief Almighty First Thunder BC", "com.yottagames.stoneage", R.drawable.question_mark, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Marvel Super War", "com.netease.g104na.gb", R.drawable.msw, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Mobile Legends Bang Bang", "com.mobile.legends", R.drawable.moblbb, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Knives Out-No rules, just fight!", "com.netease.ko", R.drawable.konrjf, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("VPN Monster", "free.vpn.unblock.proxy.vpnmonster", R.drawable.vpnm, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Rise of Civilizations", "com.lilithgame.roc.gp", R.drawable.riseoc, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("King of Avalon", "com.funplus.kingofavalonptr", R.drawable.kingoa, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Guns of Glory", "com.diandian.gog", R.drawable.gog, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Last Empire", "com.longtech.lastwars.gp", R.drawable.lasta, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("SHOPPING APPS", null, 0, AppsEvent.HEADER_TYPE));
        list.add(new AppsEvent("Romwe", "com.romwe", R.drawable.romwe, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Shein", "com.zzkko", R.drawable.shein, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("AliExpress", "com.alibaba.aliexpresshd", R.drawable.alie, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Alibaba", "com.alibaba.intl.android.apps.poseidon", R.drawable.alib, AppsEvent.ITEM_TYPE));
        list.add(new AppsEvent("Club Factory", "club.fromfactory", R.drawable.club, AppsEvent.ITEM_TYPE));
        return list;
    }

}
